# Generated by Django 2.2.16 on 2022-04-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': ('Комментарий',), 'verbose_name_plural': 'Комментарии'},
        ),
    ]
