# Generated by Django 2.2.16 on 2022-04-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220420_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата', verbose_name='Дата'),
        ),
    ]
